/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Asia/Ho_Chi_Minh' | 'UTC';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    flocks: Flock;
    products: Product;
    'feed-standards': FeedStandard;
    'policy-thresholds': PolicyThreshold;
    orders: Order;
    'wms-transactions': WmsTransaction;
    'fms-daily-logs': FmsDailyLog;
    'transfer-requests': TransferRequest;
    notifications: Notification;
    'audit-logs': AuditLog;
    'idempotency-keys': IdempotencyKey;
    exports: Export;
    imports: Import;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    flocks: FlocksSelect<false> | FlocksSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'feed-standards': FeedStandardsSelect<false> | FeedStandardsSelect<true>;
    'policy-thresholds': PolicyThresholdsSelect<false> | PolicyThresholdsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'wms-transactions': WmsTransactionsSelect<false> | WmsTransactionsSelect<true>;
    'fms-daily-logs': FmsDailyLogsSelect<false> | FmsDailyLogsSelect<true>;
    'transfer-requests': TransferRequestsSelect<false> | TransferRequestsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'idempotency-keys': IdempotencyKeysSelect<false> | IdempotencyKeysSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      importLargeFile: TaskImportLargeFile;
      reindexSearch: TaskReindexSearch;
      sendOrderNotification: TaskSendOrderNotification;
      recalculateInventory: TaskRecalculateInventory;
      sendWelcomeEmail: TaskSendWelcomeEmail;
      fmsAggregation: TaskFmsAggregation;
      auditArchive: TaskAuditArchive;
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'ADMIN' | 'OPERATOR' | 'FARM';
  fullName: string;
  phone?: string | null;
  accountStatus: 'ACTIVE' | 'LOCKED';
  tenantMemberships?: (number | Tenant)[] | null;
  tenants?: (number | Tenant)[] | null;
  authzVersion: number;
  mustChangePassword: boolean;
  primaryTenant?: (number | null) | Tenant;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * VD: FARM-BD-01, FAC-LA-02
   */
  farmCode: string;
  tenantId: string;
  name: string;
  system?: ('WMS' | 'FMS' | 'OMS' | 'TMS') | null;
  type: 'FACTORY' | 'FARM';
  status: 'ACTIVE' | 'INACTIVE' | 'LOCKED';
  flockId?: string | null;
  updatedBy?: string | null;
  managedBy?: string | null;
  managedByUser?: (number | null) | User;
  addressOfTenant?: string | null;
  phone?: string | null;
  contactEmail?: string | null;
  contactName?: string | null;
  flockName?: string | null;
  standardsApplied?: string | null;
  startFlockCount?: number | null;
  startFlockDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flocks".
 */
export interface Flock {
  id: number;
  flockId: string;
  tenant: number | Tenant;
  chickenType: string;
  initialBirdCount: number;
  startDate: string;
  flockName?: string | null;
  sourceFlockGroup?: string | null;
  standardsApplied?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  sku: string;
  name: string;
  productType: string;
  uom: string;
  uomWeightKg: number;
  stockAgeMin?: number | null;
  stockAgeMax?: number | null;
  status?: ('ACTIVE' | 'INACTIVE') | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feed-standards".
 */
export interface FeedStandard {
  id: number;
  chickenType: string;
  ageInDays: number;
  feedQtyPerBirdPerDay: number;
  cumFeedQty?: number | null;
  fcr?: number | null;
  cumDepPercent?: number | null;
  bwGr?: number | null;
  feedName?: string | null;
  migrationKey?: string | null;
  status: 'ACTIVE' | 'INACTIVE';
  standardId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-thresholds".
 */
export interface PolicyThreshold {
  id: number;
  sku: string;
  minStockDays: number;
  lowStockThreshold: number;
  criticalStockThreshold: number;
  zeroThreshold?: number | null;
  highThreshold?: number | null;
  status?: string | null;
  note?: string | null;
  thresholdId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Mã đơn được hệ thống tự động sinh (Ví dụ: WMS_1-ORD-000001)
   */
  orderId: string;
  tenant: number | Tenant;
  client: string;
  origin: number | Tenant;
  destination: number | Tenant;
  originDisplay?: string | null;
  destinationDisplay?: string | null;
  product: number | Product;
  quantity: number;
  uom?: string | null;
  status: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'REJECTED' | 'IN_TRANSIT' | 'RECEIVED' | 'COMPLETED' | 'CANCELLED';
  pickupDate?: string | null;
  expectedDeliveryDate?: string | null;
  actualDeliveryDate?: string | null;
  flock?: (number | null) | Flock;
  note?: string | null;
  migrationKey?: string | null;
  createDate?: string | null;
  location?: string | null;
  tmsOrderId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wms-transactions".
 */
export interface WmsTransaction {
  id: number;
  scope: 'FACTORY' | 'FARM';
  tenant: number | Tenant;
  flock?: (number | null) | Flock;
  product: number | Product;
  txnType: 'INBOUND' | 'OUTBOUND' | 'LOSS' | 'REPORT' | 'ADJUSTMENT' | 'CONSUME';
  quantity: number;
  order?: (number | null) | Order;
  reason?: string | null;
  date: string;
  note?: string | null;
  migrationKey?: string | null;
  transactionId?: string | null;
  dateInput?: string | null;
  ageInDays?: number | null;
  beginQuantity?: number | null;
  inQuantity?: number | null;
  outQuantity?: number | null;
  endQuantity?: number | null;
  endOrderQuantity?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fms-daily-logs".
 */
export interface FmsDailyLog {
  id: number;
  tenant: number | Tenant;
  sourceTenantId?: string | null;
  flock: number | Flock;
  date: string;
  ageInDays: number;
  birdCount?: number | null;
  feedProduct?: (number | null) | Product;
  feedQtyEst?: number | null;
  feedQtyAct?: number | null;
  feedQtyIn?: number | null;
  endQty: number;
  badgeStatus?: ('NORMAL' | 'LOW' | 'CRITICAL' | 'ZERO') | null;
  migrationKey?: string | null;
  feedState?: string | null;
  mortAct?: number | null;
  mortEst?: number | null;
  populationEst?: number | null;
  feedNameOrder?: string | null;
  feedBeginQty?: number | null;
  stockLevelPercentage?: number | null;
  currentDay?: number | null;
  dayCaseStudy?: string | null;
  sourceColumn20?: string | null;
  logId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfer-requests".
 */
export interface TransferRequest {
  id: number;
  /**
   * Mã lệnh được tự động sinh (Ví dụ: TRF-000001)
   */
  transferId: string;
  fromTenant: number | Tenant;
  toTenant: number | Tenant;
  product: number | Product;
  quantity: number;
  uom?: string | null;
  status: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'REJECTED' | 'IN_TRANSIT' | 'RECEIVED' | 'COMPLETED' | 'CANCELLED';
  requestedBy?: (number | null) | User;
  approvedBy?: (number | null) | User;
  receivedBy?: (number | null) | User;
  flock?: (number | null) | Flock;
  note?: string | null;
  migrationKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | User;
  type:
    | 'ORDER_APPROVED'
    | 'ORDER_REJECTED'
    | 'ORDER_INCOMING'
    | 'ORDER_RECEIVED'
    | 'ORDER_COMPLETED'
    | 'ORDER_ISSUE'
    | 'TRANSFER_APPROVED'
    | 'TRANSFER_REJECTED'
    | 'TRANSFER_INCOMING'
    | 'TRANSFER_RECEIVED'
    | 'TRANSFER_COMPLETED'
    | 'TRANSFER_ISSUE';
  title: string;
  message: string;
  relatedOrder?: (number | null) | Order;
  relatedTransfer?: (number | null) | TransferRequest;
  isRead?: boolean | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  actorUserId: number | User;
  actorEmail: string;
  actorRole: string;
  action: string;
  targetCollection: string;
  targetId: string;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  userAgent?: string | null;
  timestamp: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "idempotency-keys".
 */
export interface IdempotencyKey {
  id: number;
  key: string;
  collection: string;
  action: string;
  resultId?: string | null;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'tenants';
        value: number | Tenant;
      }
    | {
        relationTo: 'flocks';
        value: number | Flock;
      }
    | {
        relationTo: 'products';
        value: number | Product;
      }
    | {
        relationTo: 'orders';
        value: number | Order;
      }
    | {
        relationTo: 'transfer-requests';
        value: number | TransferRequest;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'importLargeFile'
          | 'reindexSearch'
          | 'sendOrderNotification'
          | 'recalculateInventory'
          | 'sendWelcomeEmail'
          | 'fmsAggregation'
          | 'auditArchive'
          | 'createCollectionExport'
          | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'importLargeFile'
        | 'reindexSearch'
        | 'sendOrderNotification'
        | 'recalculateInventory'
        | 'sendWelcomeEmail'
        | 'fmsAggregation'
        | 'auditArchive'
        | 'createCollectionExport'
        | 'createCollectionImport'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'flocks';
        value: number | Flock;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'feed-standards';
        value: number | FeedStandard;
      } | null)
    | ({
        relationTo: 'policy-thresholds';
        value: number | PolicyThreshold;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'wms-transactions';
        value: number | WmsTransaction;
      } | null)
    | ({
        relationTo: 'fms-daily-logs';
        value: number | FmsDailyLog;
      } | null)
    | ({
        relationTo: 'transfer-requests';
        value: number | TransferRequest;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'idempotency-keys';
        value: number | IdempotencyKey;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  fullName?: T;
  phone?: T;
  accountStatus?: T;
  tenantMemberships?: T;
  tenants?: T;
  authzVersion?: T;
  mustChangePassword?: T;
  primaryTenant?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  farmCode?: T;
  tenantId?: T;
  name?: T;
  system?: T;
  type?: T;
  status?: T;
  flockId?: T;
  updatedBy?: T;
  managedBy?: T;
  managedByUser?: T;
  addressOfTenant?: T;
  phone?: T;
  contactEmail?: T;
  contactName?: T;
  flockName?: T;
  standardsApplied?: T;
  startFlockCount?: T;
  startFlockDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flocks_select".
 */
export interface FlocksSelect<T extends boolean = true> {
  flockId?: T;
  tenant?: T;
  chickenType?: T;
  initialBirdCount?: T;
  startDate?: T;
  flockName?: T;
  sourceFlockGroup?: T;
  standardsApplied?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  sku?: T;
  name?: T;
  productType?: T;
  uom?: T;
  uomWeightKg?: T;
  stockAgeMin?: T;
  stockAgeMax?: T;
  status?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feed-standards_select".
 */
export interface FeedStandardsSelect<T extends boolean = true> {
  chickenType?: T;
  ageInDays?: T;
  feedQtyPerBirdPerDay?: T;
  cumFeedQty?: T;
  fcr?: T;
  cumDepPercent?: T;
  bwGr?: T;
  feedName?: T;
  migrationKey?: T;
  status?: T;
  standardId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-thresholds_select".
 */
export interface PolicyThresholdsSelect<T extends boolean = true> {
  sku?: T;
  minStockDays?: T;
  lowStockThreshold?: T;
  criticalStockThreshold?: T;
  zeroThreshold?: T;
  highThreshold?: T;
  status?: T;
  note?: T;
  thresholdId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderId?: T;
  tenant?: T;
  client?: T;
  origin?: T;
  destination?: T;
  originDisplay?: T;
  destinationDisplay?: T;
  product?: T;
  quantity?: T;
  uom?: T;
  status?: T;
  pickupDate?: T;
  expectedDeliveryDate?: T;
  actualDeliveryDate?: T;
  flock?: T;
  note?: T;
  migrationKey?: T;
  createDate?: T;
  location?: T;
  tmsOrderId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wms-transactions_select".
 */
export interface WmsTransactionsSelect<T extends boolean = true> {
  scope?: T;
  tenant?: T;
  flock?: T;
  product?: T;
  txnType?: T;
  quantity?: T;
  order?: T;
  reason?: T;
  date?: T;
  note?: T;
  migrationKey?: T;
  transactionId?: T;
  dateInput?: T;
  ageInDays?: T;
  beginQuantity?: T;
  inQuantity?: T;
  outQuantity?: T;
  endQuantity?: T;
  endOrderQuantity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fms-daily-logs_select".
 */
export interface FmsDailyLogsSelect<T extends boolean = true> {
  tenant?: T;
  sourceTenantId?: T;
  flock?: T;
  date?: T;
  ageInDays?: T;
  birdCount?: T;
  feedProduct?: T;
  feedQtyEst?: T;
  feedQtyAct?: T;
  feedQtyIn?: T;
  endQty?: T;
  badgeStatus?: T;
  migrationKey?: T;
  feedState?: T;
  mortAct?: T;
  mortEst?: T;
  populationEst?: T;
  feedNameOrder?: T;
  feedBeginQty?: T;
  stockLevelPercentage?: T;
  currentDay?: T;
  dayCaseStudy?: T;
  sourceColumn20?: T;
  logId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfer-requests_select".
 */
export interface TransferRequestsSelect<T extends boolean = true> {
  transferId?: T;
  fromTenant?: T;
  toTenant?: T;
  product?: T;
  quantity?: T;
  uom?: T;
  status?: T;
  requestedBy?: T;
  approvedBy?: T;
  receivedBy?: T;
  flock?: T;
  note?: T;
  migrationKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  title?: T;
  message?: T;
  relatedOrder?: T;
  relatedTransfer?: T;
  isRead?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  actorUserId?: T;
  actorEmail?: T;
  actorRole?: T;
  action?: T;
  targetCollection?: T;
  targetId?: T;
  before?: T;
  after?: T;
  ip?: T;
  userAgent?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "idempotency-keys_select".
 */
export interface IdempotencyKeysSelect<T extends boolean = true> {
  key?: T;
  collection?: T;
  action?: T;
  resultId?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskImportLargeFile".
 */
export interface TaskImportLargeFile {
  input: {
    fileUrl: string;
    collection: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskReindexSearch".
 */
export interface TaskReindexSearch {
  input: {
    collection?: string | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendOrderNotification".
 */
export interface TaskSendOrderNotification {
  input: {
    orderId: string;
    newStatus: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRecalculateInventory".
 */
export interface TaskRecalculateInventory {
  input: {
    tenantId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendWelcomeEmail".
 */
export interface TaskSendWelcomeEmail {
  input: {
    userId: string;
    email: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFmsAggregation".
 */
export interface TaskFmsAggregation {
  input: {
    date: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskAuditArchive".
 */
export interface TaskAuditArchive {
  input: {
    beforeDate: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'users'
      | 'tenants'
      | 'flocks'
      | 'products'
      | 'feed-standards'
      | 'policy-thresholds'
      | 'orders'
      | 'wms-transactions'
      | 'fms-daily-logs'
      | 'transfer-requests'
      | 'notifications'
      | 'audit-logs'
      | 'idempotency-keys'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}